### PR TITLE
Toplevel for REPL driven development

### PR DESCRIPTION
**Pull request by callistonianembrace**
`rtop` doesn't understand OCaml syntax emitted by `dune top` and needs a workaround - load the `cma` files first from the `use_output`, then activate the reason parsers in the REPL.

We could take this up in the Reason community and see if this can be fixed natively there.

### CODE REVIEW

**Comment by callistonianembrace** [comment]
To test the REPL - ` esy b dune exec ./tools/dtop.exe`

**Comment by anchpop** [comment]
I get this output when running that command:

```
node ➜ /workspaces/sidechain (callistonianembrace/add-rtop) $ esy b dune exec ./tools/dtop.exe
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "open", "/home/node/.config/.lambda-term-inputrc")
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
```

Do I need to install rtop? If so, can it be included in the package.json so it's installed automatically after running `esy install`?

**Comment by callistonianembrace** [comment]
@anchpop Can you `touch /home/node/.config/.lambda-term-inputrc` the file?

**Comment by anchpop** [comment]
@callistonianembrace I also had to create `/home/node/.rtop-history` and `/home/node/.utoprc` in addition to `/home/node/.config/.lambda-term-inputrc`, but now it seems to work. Should I include commands to touch those in my docker configuration, or is there a different recommended way to set up an environment for rtop?

**Review by anchpop — APPROVED** [review]

**Comment by callistonianembrace** [comment]
>  Should I include commands to touch those in my docker configuration, or is there a different recommended way to set up an environment for rtop?

@anchpop Yes, please touch those files.

**Comment by EduardoRFS** [comment]
I don't like this, utop has a reason mode right? Why can't we just use it instead?

**Comment by callistonianembrace** [comment]
@EduardoRFS I'm not sure what you're referring to. How do I try out this reason mode you're talking about?

**Comment by EduardoRFS** [comment]
@callistonianembrace I don't remember that much, but isn't this https://github.com/ocaml-community/utop/blob/bac3946079a98df00f31656dc10c6c9f1a8bc422/src/top/utop.el#L264 ?

**Comment by callistonianembrace** [comment]
@EduardoRFS That's an emacs plugin - utop minor mode works with reason major mode.

**Comment by EduardoRFS** [comment]
Opened a follow up #118

**Comment by EduardoRFS** [comment]
anime girl saying nice to developer experience being improved

**Pull request merged**
